baseURL = 'https://nathantebbs.com'
languageCode = 'en-us'
title = 'Nathan Tebbs'
theme = 'typo'

[params]
description = "A Tech Blog"

customCSS = ["css/custom.css"]

theme = 'auto'
colorPallete = 'default'
hideHeader = false

homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a Computer Science student at University of Arizona in Tucson, Arizona, 
with a strong background in cloud computing and python. Solving complex
problems is my passion, and my interests include databases, developer tools,
computer networking, and C/C++ programming.
"""

homeCollectionTitle = 'Posts'
homeCollection = 'posts'

paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ntebbs/"

[[params.social]]
name = "github"
url = "https://github.com/nathantebbs"

# Main menu
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlighting on code blocks.
[markup]
[markup.highligh]
stle = 'algol'

[markup.goldmark.renderer]
unsafe = true
